# Generated by Django 5.1.5 on 2025-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=12),
        ),
    ]
