# Generated by Django 5.1.5 on 2025-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
